### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops-mpi#122]
A number of new features have been implemented since our last release in April. I think it is a good time to release v0.2.0 😄

**Comment by rohanbabbar04** [comment]
Sounds good
Let me release a new version on Monday

**Comment by mrava87** [comment]
Thanks 🙏

**Comment by mrava87** [comment]
@rohanbabbar04 I saw you released the new version but didn't update the changelog files, should I do it?

**Comment by rohanbabbar04** [comment]
Oops forgot about those let me update them
