### ISSUE TITLE
Publish PyLops-MPI on Zenodo

### ISSUE THREAD

**Issue by rohanbabbar04** [PyLops/pylops-mpi#124]
We need to publish our software to Zenodo for our research paper. @mrava87, since you are the owner of the repo, could you publish it? 
Here is a helpful link: [Github-Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)

**Comment by mrava87** [comment]
Done :) but it seems like you need to make a new release for the DOI to be triggered 😄

**Comment by mrava87** [comment]
<img width="964" alt="Screenshot 2024-12-20 at 20 22 04" src="https://github.com/user-attachments/assets/c255dc12-d38f-4651-9795-f6a6f302c066" />

**Comment by rohanbabbar04** [comment]
Yup,
We need to make a new release to trigger it l
Let's release v0.2.1 to trigger the publication

**Comment by mrava87** [comment]
Please make the release and I will tell you the DOI 😊

**Comment by rohanbabbar04** [comment]
I just made a release, and I can see it on Zenodo, but I can't see the ORCID information of the authors. @mrava87 can you please look into it
Thanks

**Comment by mrava87** [comment]
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.14539781.svg)](https://doi.org/10.5281/zenodo.14539781)
