### ISSUE TITLE
Poststack inversion

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops-mpi#34]
Add the following parts to the example `plot_post_stack_inversion`:

- [x] inversion using the newly developed CGLS solver. 
- [ ] inversion with regularization: ~~for now we can also show how to add regularization over the 2 axes that are not distributed. This simply means making an operator for each rank that looks like:~~

```
PPop = PoststackLinearModelling(wav, nt0=nz, spatdims=(ny_i, nx))
Top = Transpose((ny_i, nx, nz), (2, 0, 1))
DxOp = SecondDerivative(...)
DzOp = SecondDerivative(...)

eps = # reg parameter
BDiag = MPIBlockDiag(ops=[Top.H @ PPop @ Top, eps * DxOp, eps * DzOp ])
```

~~and stacking d_dist with 2 vectors of zeros of the size of the local portion of the model.~~ Use pylops_mpi.Laplacian operator.

- [x] I would also suggest including an equation at the top of the tutorial explaining how the problem can be written mathematically in a distributed fashion (including the regularizer)

**Comment by rohanbabbar04** [comment]
@mrava87 for the inversion portion
will we be working on two methods
- one will be cgls(like we have done lsqr for 2d)
- And second as you mentioned inv with regularization

**Comment by rohanbabbar04** [comment]
I think now we can revisit this...
With `MPISecondDerivative` now ready maybe you can add another point here for updating the example....

**Comment by mrava87** [comment]
Indeed
