### ISSUE TITLE
Least-squares migration

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops-mpi#46]
To showcase the `pylops_mpi.MPIVStack` operator on a real life problem, we can now create a tutorial based on https://pylops.readthedocs.io/en/stable/tutorials/lsm.html#sphx-glr-tutorials-lsm-py

Basically, the main difference with the original tutorial stems from the fact that we partition `sources` between ranks, something like this: 

```
rank = MPI.COMM_WORLD.Get_rank()
size = MPI.COMM_WORLD.Get_size()
...

# Sources 
nstot = 10
ns = nstot // size 
sxtot = np.linspace(dx * 10, (nx - 10) * dx, ns)
sx = sxtot[rank*ns:(rank+1)*ns] 
sz = 10 * np.ones(ns) 
sources = np.vstack((sx, sz)) 
ds = sources[0, 1] - sources[0, 0]
```

The rest should stay the same, with of course the addition of `pylops_mpi.MPIVStack` and the `pylops_mpi.optimization.basic.cgls`

**Comment by rohanbabbar04** [comment]
I had one doubt over here 
```
nstot = 10
ns = nstot // size 
```
In the above case if the size=3, the `ns` at each rank will be 3(which does not sum up to 10), would that be right or are we going to ask the user to specify the size divisible by `nstot`.
I thought about putting into the distributed array giving local shape (4, 3, 3) in three ranks. Then I realized lsm uses Kirchoff which gives the shape of (ns, nr, nt), so for rank=0, ns will be 4 and causes issues when applying matvec..

**Comment by mrava87** [comment]
@rohanbabbar04 sorry, I didn’t see your question. Ideally one has nstot from an experiment and this may not be fully divisible by the number of MPI ranks selected. 

If I remember correctly, the DistributedArray has the first n-1 ranks with the same size and the last one with the slightly smaller/bigger depending on the total size, isn’t it?

As this example uses a VStack operator, technically it should not be a problem to have individual operators in different ranks with slightly different size. Is this currently not allowed? I am not sure I get why the problem would be the Kirchhoff operator, what would happen if you split (3,3,4)?
