### ISSUE TITLE
SecondDerivative and Laplacian

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops-mpi#56]
Next steps after `pylops_mpi.FirstDerivative` is finalized:

- [x] Follow the same steps of `pylops_mpi.FirstDerivative` with the SecondDerivative operator
- [x] Write `pylops_mpi.Laplacian`: here since we have to sum two for 2Darray (or N for NDarray) second derivatives, I see the need to combine the new `pylops_mpi.SecondDerivative` for the axis where distribution is performed, and a `pylops_mpi.BlockDiag([pylops.SecondDerivative,]` for the other axes 
- [x] Make example showcasing all Derivative-related operators

**Comment by rohanbabbar04** [comment]
@mrava87, in the `pylops_mpi.MPILaplacian` example I understand that we apply MPISecondDerivative along axis=0, but what will we do for the other axes. 
Can you explain this :point_down: 
 ```
a pylops_mpi.BlockDiag([pylops.SecondDerivative,] for the other axes
```

**Comment by mrava87** [comment]
Hi Rohan, 
in Laplacian you apply second derivatives along 2 or more chosen axes. 

Here, the idea is that you can just apply pylops.SecondDerivative (wrapped into MPILinearOperator) over n-1 axes, however this cannot be done for axis=0 when the input is a scattered DistributedArray… there we need to use the new pulps_mpi.SecondDerivative instead :)

makes sense?

**Comment by rohanbabbar04** [comment]
I see
So for the axis=0, we can go for `pylops_mpi.MPISecondDerivative(dims, ...)` which is clear 
For the other axes we do a `pylops_mpi.MPIBlockDiag(ops=[pylops.SecondDerivative(dims, ....), ]`
Is this right or will the dims be different bcoz from what i see doing a matvec(shape of blockdiag != shape of MPISecondDerivative) would give different output shapes and cannot sum it for final output.
Maybe I am wrong in understanding or proceeding with it..

**Comment by mrava87** [comment]
Mmh let me try making an example. You have a 2d distributed array of size (nx, nz) with nx divisible by the number of processes uses. So each rank has locally an array of size (nx//size, ny)… of course the vector will have to be 1D but since things are divisible each will still have nx//size*nz elements that correspond to a portion of the x axis.

Now Laplacian will need to have d2m/dx2+d2m/dy2 (I call m the input vector): for the first one we use the new SecondDerivative, input and output are both scattered arrays with same segments, for the second one since each rank has the entire z direction you split the second derivative via MPIBlockDiag, again the input and output are the same… so things should work easily I think :) if you still struggle to understand I can have a go at it

**Comment by rohanbabbar04** [comment]
Thanks @mrava87, I have done it for `nx%size==0` and will push it soon, but what if it is not fully divisible by size?
Will we be using MPILaplacian in the below manner
```
ny_i, nx, nz = (10, 20, 30)
ny = MPI.COMM_WORLD.allgather(ny_i)
# Then we will apply MPILaplacian to avoid non-divisibility case
lap = MPILaplacian(dims=(ny, nx, nz), ...)
x = DistributedArray(global_shape=ny * nx * nz)
x[:] = 1
print(lap @ x)
```

**Comment by mrava87** [comment]
Great!

I guess you mean ny?

I think this is a scenario where giving users access to local_shape is needed. Provided we split x such that each rank has a slice of size (ny_i, nx, nz) then things should work fine. I don’t recall, could MPIBlockDiag not handle slightly different size of operators in different ranks?

**Comment by mrava87** [comment]
And yes, the code you provide is pretty much like I see this operator being used most of the time :)

**Comment by rohanbabbar04** [comment]
> Great!
> 
> I guess you mean ny?
> 
> I think this is a scenario where giving users access to local_shape is needed. Provided we split x such that each rank has a slice of size (ny_i, nx, nz) then things should work fine. I don’t recall, could MPIBlockDiag not handle slightly different size of operators in different ranks (basically ny_i different from rank to rank, say 11,10,10 for a case of size=3)?

Yup I meant `ny`.
For your question when it comes to 3-d and post-stack, having (11, 20, 10); (10, 20, 10) ; (10, 20, 10)and with blockdiag being (6200, 6200);
Now when we apply matvec with array of 6200 it will undergo a partition of 6200//3 which will not match the dims at each rank.
I think we discussed it and that is why we added an error which will ask the user to reshape the array before inputting it in...

**Comment by mrava87** [comment]
Alright, I see. But there is one thing we agreed that may fix this (maybe?): what about if we add `local_shape` to DistributedArray so that this scenario can be gracefully prevented. I just created an issue to make sure we don't forget about doing it (https://github.com/PyLops/pylops-mpi/issues/59).

`why we added an error which will ask the user to reshape the array before inputting it in`: where is this, I am not sure I understand

**Comment by mrava87** [comment]
Great! And for sure adding the `reshaped` decorators to other classes is also something worth doing... as we discussed this should be the under-the-hood cheap solution for users that do not want full performance, whilst the local_shape should be there for those that dont want to have any penalty for extra communication :)

**Comment by rohanbabbar04** [comment]
I think we can close this issue...
