### ISSUE TITLE
Gradient 

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops-mpi#62]
I suggest to finalize the suite of derivative operators but adding also Gradient as the MPI version of pylops.Gradient.

This should be almost identical to Laplacian with the only difference that we will stack various first derivatives instead of summing them… the only thing I’m not so sure is if our VStack is ready/suitable yet to stacking other pylops_mpi operators? And if this is not the case, how easy it would be to enable this pattern?

**Comment by rohanbabbar04** [comment]
Hi @mrava87 , If I am not wrong we will be using the `MPIStackedVStack` operator over here to stack the pylops_mpi FirstDerivative Operator. So we need to extend the `Gradient` class to `MPIStackedLinearOperator`.
What do you think, as it will prevent us from performing operations with `MPILinearOperator`, to perform operations with `MPILinearOperator` we need to fit it in a `MPIStackedVStack` or `MPIStackedBlockDiag`?

**Comment by mrava87** [comment]
@rohanbabbar04, I did not think about this before as I kind of expected to be very similar to `Laplacian`, but I think you are correct.

In `Laplacian`, we sum SecondDerivative operators so it makes sense that we can work with `DistributedArray` in both input and output, but here we vertically stack FirstDerivative operators and so the output will have to be of `MPIStackedLinearOperator` type... I do not think we can make this operator a `MPILinearOperator` type of operator

**Comment by rohanbabbar04** [comment]
Hmm... 
I think for all the other main operations it will work perfectly, but for Sum and Product we would need to stack the MPILinearOperator in one of the StackedLinearOperators.
Something like this..
```
Sop = MPIGradient(...) + MPIStackVStack(ops=[MPILaplacian(...)])
```

**Comment by mrava87** [comment]
I am not sure one would ever do this kind of sum as gradient usually makes the output N times bigger than the input (N=number of dimensions of dims) whilst Laplacian keeps the same size of input… so to make your code snipped work one would need to put N laplacians into ops :)

**Comment by rohanbabbar04** [comment]
Ok Thanks....
I will implement it by extending `Gradient` with `MPIStackedLinearOperator`
