### ISSUE TITLE
Test bed for pylops-mpi

### ISSUE THREAD

**Issue by rohanbabbar04** [PyLops/pylops-mpi#67]
> I can make the GitHub action so I can use the same secret used for other libraries in the Pylops organization. In the meantime, one thing you could try to do is to see if you can build the package locally and push it to https://test.pypi.org/. 

- [x] Push to test.pypi [ pylops-mpi](https://test.pypi.org/project/pylops-mpi/)

**Comment by rohanbabbar04** [comment]
@mrava87 Pushed it to test pypi, got very minor error which I have solved and pushed

**Comment by mrava87** [comment]
Great!

I have already added the secret into the setting of the repo (https://github.com/PyLops/pylops-mpi/settings/secrets/actions), I will make a PR adding the same GitHub action for deploy we use in PyLops here https://github.com/PyLops/pylops/blob/dev/.github/workflows/deploy.yaml (I believe this does pretty much your steps apart from the last one as this is handled by the gh-action publishing step itself :)

After that I suggest we wait until the end of GSoC, and then we can make our first release :) this can be done by anyone with admin permissions on the repo (you included) by making a release in GitHub, which will trigger the action and push to PyPI :)

**Comment by mrava87** [comment]
Just to be sure, did you check that you can now do pip install this library in a clean environment?

**Comment by rohanbabbar04** [comment]
Yup checked it seems to work fine for me.
```
pip install --extra-index-url https://test.pypi.org/simple/ pylops-mpi
```

**Comment by mrava87** [comment]
Perfect, then we should be in good shape and things should work fine also when we do it on the official PyPI with the first release (see my PR) :)

**Comment by rohanbabbar04** [comment]
Completed with #74
