### ISSUE TITLE
Cg and Cgls with DistributedArray/StackDistributedArray

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops-mpi#87]
In https://github.com/PyLops/pylops-mpi/pull/86/, the `cg` and `cgls` solvers have been modified to handle `DistributedArray` and `StackDistributedArray` interchangeably.

This change is however sub-optimal in some places where in-place operations have been replaced by operations that re-initialize a `DistributedArray` or `StackDistributedArray`, eg:

```
self.c[:] = self.r.local_array + b * self.c.local_array
```

to
```
self.c = self.r + b * self.c
```

We should decide whether this is the best way or another approach could be taken to avoid re-initialization without having to create branched codes for the different type of arrays

**Comment by rohanbabbar04** [comment]
So @mrava87, I looked into this some changes which we will be implemented
- Update the docs 
- For the case when `x0` is not provided it will return an error(we will need to handle this...).
- I will think if we can do something else for `self.c = self.r + b * self.c`

**Comment by mrava87** [comment]
@rohanbabbar04 thanks for looking into this!

For `x0`, I think we can make breaking changes at this point of development, especially if those are reasoned and comes from new features that we did not envision at the time we developed the solvers. I would be tempted to say that the best way to transparently handle this is just make `x0` mandatory and not optional :)

**Comment by rohanbabbar04** [comment]
> @rohanbabbar04 thanks for looking into this!
> 
> For `x0`, I think we can make breaking changes at this point of development, especially if those are reasoned and comes from new features that we did not envision at the time we developed the solvers. I would be tempted to say that the best way to transparently handle this is just make `x0` mandatory and not optional :)

So, we make x0 compulsory for both `MPILinearOperator` and `MPIStackedLinearOperator`?

**Comment by mrava87** [comment]
No I mean for the solvers, MPILinearOperator and MPIStackedLinearOperator do not have any x0

**Comment by rohanbabbar04** [comment]
Got it let me do it this week...
